/*
 * Automatically generated header file: don't edit
 */

//#define HAVE_DOT_CONFIG 1
#define CONFIG_PLATFORM_LINUX 1
//#undef CONFIG_PLATFORM_CYGWIN
//#undef CONFIG_PLATFORM_WIN32

/*
 * General Configuration
 */
#ifdef PREFIX
#define PREFIX "/usr/local"
#else
#define PREFIX ""
#endif
//#undef CONFIG_DEBUG
//#define CONFIG_STRIP_UNWANTED_SECTIONS 1
#undef CONFIG_VISUAL_STUDIO_7_0
#undef CONFIG_VISUAL_STUDIO_8_0
#undef CONFIG_VISUAL_STUDIO_10_0
#define CONFIG_VISUAL_STUDIO_7_0_BASE ""
#define CONFIG_VISUAL_STUDIO_8_0_BASE ""
#define CONFIG_VISUAL_STUDIO_10_0_BASE ""
#define CONFIG_EXTRA_CFLAGS_OPTIONS ""
#define CONFIG_EXTRA_LDFLAGS_OPTIONS ""

/*
 * SSL Library
 */
//#undef CONFIG_SSL_SERVER_ONLY
//#undef CONFIG_SSL_CERT_VERIFICATION
//#undef CONFIG_SSL_ENABLE_CLIENT
//#define CONFIG_SSL_FULL_MODE 1
//#undef CONFIG_SSL_SKELETON_MODE
//#undef CONFIG_SSL_PROT_LOW
//#define CONFIG_SSL_PROT_MEDIUM 1
//#undef CONFIG_SSL_PROT_HIGH
//#define CONFIG_SSL_USE_DEFAULT_KEY 1
#if CONFIG_SSL_PRIVATE_KEY_LOCATION == ""
#define CONFIG_SSL_PRIVATE_KEY_LOCATION ""
#else
#define CONFIG_SSL_PRIVATE_KEY_LOCATION "X"
#endif
#if CONFIG_SSL_PRIVATE_KEY_PASSWORD == ""
#define CONFIG_SSL_PRIVATE_KEY_PASSWORD ""
#else
#define CONFIG_SSL_PRIVATE_KEY_PASSWORD "X"
#endif
#if CONFIG_SSL_X509_CERT_LOCATION == ""
#define CONFIG_SSL_X509_CERT_LOCATION ""
#else
#define CONFIG_SSL_X509_CERT_LOCATION "X"
#endif
//#undef CONFIG_SSL_GENERATE_X509_CERT
#if CONFIG_SSL_X509_COMMON_NAME
#define CONFIG_SSL_X509_COMMON_NAME ""
#else
#define CONFIG_SSL_X509_COMMON_NAME "X"
#endif
#if CONFIG_SSL_X509_ORGANIZATION_NAME
#define CONFIG_SSL_X509_ORGANIZATION_NAME ""
#else
#define CONFIG_SSL_X509_ORGANIZATION_NAME "X"
#endif
#if CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME
#define CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME ""
#else
#define CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME "X"
#endif
//#define CONFIG_SSL_HAS_PEM 1
//#define CONFIG_SSL_USE_PKCS12 1
#if CONFIG_SSL_EXPIRY_TIME == 24
#define CONFIG_SSL_EXPIRY_TIME 24
#else
#define CONFIG_SSL_EXPIRY_TIME 1
#endif
#if CONFIG_X509_MAX_CA_CERTS == 150
#define CONFIG_X509_MAX_CA_CERTS 150
#else
#define CONFIG_X509_MAX_CA_CERTS 4
#endif
#if CONFIG_SSL_MAX_CERTS == 3
#define CONFIG_SSL_MAX_CERTS 3
#else
#define CONFIG_SSL_MAX_CERTS 2
#endif
//#undef CONFIG_SSL_CTX_MUTEXING
//#define CONFIG_USE_DEV_URANDOM 1
//#undef CONFIG_WIN32_USE_CRYPTO_LIB
//#undef CONFIG_OPENSSL_COMPATIBLE
//#undef CONFIG_PERFORMANCE_TESTING
//#undef CONFIG_SSL_TEST
//#undef CONFIG_AXTLSWRAP
//#define CONFIG_AXHTTPD 1

/*
 * Axhttpd Configuration
 */
//#undef CONFIG_HTTP_STATIC_BUILD
#if CONFIG_HTTP_PORT == 80
#define CONFIG_HTTP_PORT 80
#else
#define CONFIG_HTTP_PORT 88
#endif
#if CONFIG_HTTP_HTTPS_PORT == 443
#define CONFIG_HTTP_HTTPS_PORT 443
#else
#define CONFIG_HTTP_HTTPS_PORT 42
#endif
#if CONFIG_HTTP_SESSION_CACHE_SIZE == 5
#define CONFIG_HTTP_SESSION_CACHE_SIZE 5
#else
#define CONFIG_HTTP_SESSION_CACHE_SIZE 1
#endif
#if CONFIG_HTTP_WEBROOT == "../www"
#define CONFIG_HTTP_WEBROOT "../www"
#else
#define CONFIG_HTTP_WEBROOT "../www3"
#endif
#if CONFIG_HTTP_TIMEOUT == 300
#define CONFIG_HTTP_TIMEOUT 300
#else
#define CONFIG_HTTP_TIMEOUT 600
#endif

/*
 * CGI
 */
//#define CONFIG_HTTP_HAS_CGI 1
#if CONFIG_HTTP_CGI_EXTENSIONS == ".lua,.lp,.php"
#define CONFIG_HTTP_CGI_EXTENSIONS ".lua,.lp,.php"
#else
#define CONFIG_HTTP_CGI_EXTENSIONS ""
#endif
//#define CONFIG_HTTP_ENABLE_LUA 1
#if CONFIG_HTTP_LUA_PREFIX == "/usr"
#define CONFIG_HTTP_LUA_PREFIX "/usr"
#else
#define CONFIG_HTTP_LUA_PREFIX ""
#endif
//#undef CONFIG_HTTP_BUILD_LUA
#if CONFIG_HTTP_CGI_LAUNCHER == "/usr/bin/cgi"
#define CONFIG_HTTP_CGI_LAUNCHER "/usr/bin/cgi"
#else
#define CONFIG_HTTP_CGI_LAUNCHER ""
#endif
//#define CONFIG_HTTP_DIRECTORIES 1
//#define CONFIG_HTTP_HAS_AUTHORIZATION 1
//#undef CONFIG_HTTP_HAS_IPV6
//#undef CONFIG_HTTP_ENABLE_DIFFERENT_USER
#if CONFIG_HTTP_USER == ""
#define CONFIG_HTTP_USER ""
#else
#define CONFIG_HTTP_USER "usr"
#endif
//#define CONFIG_HTTP_VERBOSE 1
//#undef CONFIG_HTTP_IS_DAEMON

/*
 * Language Bindings
 */
//#undef CONFIG_BINDINGS
//#undef CONFIG_CSHARP_BINDINGS
//#undef CONFIG_VBNET_BINDINGS
#if CONFIG_DOT_NET_FRAMEWORK_BASE == ""
#define CONFIG_DOT_NET_FRAMEWORK_BASE ""
#else
#define CONFIG_DOT_NET_FRAMEWORK_BASE "c:\\WINDOWS\\Microsoft.NET\\Framework\\v2.0.50727"  
#endif
//#undef CONFIG_JAVA_BINDINGS
#if CONFIG_JAVA_HOME == ""
#define CONFIG_JAVA_HOME ""
#else
#define CONFIG_JAVA_HOME "/usr/lib/jvm/java-7-openjdk-amd64"
#endif
//#undef CONFIG_PERL_BINDINGS
#if CONFIG_PERL_CORE == ""
#define CONFIG_PERL_CORE ""
#else
#define CONFIG_PERL_CORE "c:\\perl\\lib\\CORE"
#endif
#if CONFIG_PERL_LIB == ""
#define CONFIG_PERL_LIB ""
#else
#define CONFIG_PERL_LIB "perl58.lib"
#endif
//#undef CONFIG_LUA_BINDINGS
#if CONFIG_LUA_CORE == ""
#define CONFIG_LUA_CORE ""
#else
#define CONFIG_LUA_CORE "/usr/local"
#endif
/*
 * Samples
 */
//#define CONFIG_SAMPLES 1
//#define CONFIG_C_SAMPLES 1
//#undef CONFIG_CSHARP_SAMPLES
//#undef CONFIG_VBNET_SAMPLES
//#undef CONFIG_JAVA_SAMPLES
//#undef CONFIG_PERL_SAMPLES
//#undef CONFIG_LUA_SAMPLES

/*
 * BigInt Options
 */
//#undef CONFIG_BIGINT_CLASSICAL
//#undef CONFIG_BIGINT_MONTGOMERY
//#define CONFIG_BIGINT_BARRETT 1
//#define CONFIG_BIGINT_CRT 1
//#undef CONFIG_BIGINT_KARATSUBA
#if MUL_KARATSUBA_THRESH == 20
#define MUL_KARATSUBA_THRESH 20
#else
#define MUL_KARATSUBA_THRESH 2
#endif
#if SQU_KARATSUBA_THRESH == 40
#define SQU_KARATSUBA_THRESH 40
#else
#define SQU_KARATSUBA_THRESH 4
#endif
//#define CONFIG_BIGINT_SLIDING_WINDOW 1
//#define CONFIG_BIGINT_SQUARE 1
//#undef CONFIG_BIGINT_CHECK_ON
//#define CONFIG_INTEGER_32BIT 1
//#undef CONFIG_INTEGER_16BIT
//#undef CONFIG_INTEGER_8BIT
