#define KGEN_x25 ((!defined KGENMACRO_CONFIG_INTEGER_16BIT))
#define KGEN_x23 ((!defined KGENMACRO_CONFIG_INTEGER_32BIT))
#define KGEN_x28 ((!defined KGENMACRO_CONFIG_INTEGER_8BIT))
#define KGEN_x34 ((!defined KGENMACRO_CONFIG_BIGINT_MONTGOMERY))
#define KGEN_x32 ((!defined KGENMACRO_CONFIG_BIGINT_CLASSICAL))
#define KGEN_x37 ((!defined KGENMACRO_CONFIG_BIGINT_BARRETT))
#define KGEN_x43 ((!defined KGENMACRO_CONFIG_SSL_PROT_MEDIUM))
#define KGEN_x41 ((!defined KGENMACRO_CONFIG_SSL_PROT_LOW))
#define KGEN_x46 ((!defined KGENMACRO_CONFIG_SSL_PROT_HIGH))
#define KGEN_x52 ((!defined KGENMACRO_CONFIG_SSL_CERT_VERIFICATION))
#define KGEN_x50 ((!defined KGENMACRO_CONFIG_SSL_SERVER_ONLY))
#define KGEN_x55 ((!defined KGENMACRO_CONFIG_SSL_ENABLE_CLIENT))
#define KGEN_x58 ((!defined KGENMACRO_CONFIG_SSL_FULL_MODE))
#define KGEN_x61 ((!defined KGENMACRO_CONFIG_SSL_SKELETON_MODE))
#define KGEN_x72 ((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0))
#define KGEN_x70 ((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0))
#define KGEN_x75 ((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0))
#define KGEN_x81 ((!defined KGENMACRO_CONFIG_PLATFORM_CYGWIN))
#define KGEN_x79 ((!defined KGENMACRO_CONFIG_PLATFORM_LINUX))
#define KGEN_x84 ((!defined KGENMACRO_CONFIG_PLATFORM_WIN32))
#define KGEN_x90 ((defined KGENMACRO_CONFIG_INTEGER_32BIT||defined KGENMACRO_CONFIG_INTEGER_16BIT||defined KGENMACRO_CONFIG_INTEGER_8BIT))
#define KGEN_x96 (((KGEN_x61)||(!(KGEN_x90))))
#define KGEN_x95 ((defined KGENMACRO_CONFIG_INTEGER_32BIT||defined KGENMACRO_CONFIG_INTEGER_16BIT||defined KGENMACRO_CONFIG_INTEGER_8BIT||defined KGENMACRO_CONFIG_SSL_SKELETON_MODE))
#define KGEN_x91 ((defined KGENMACRO_CONFIG_BIGINT_CLASSICAL||defined KGENMACRO_CONFIG_BIGINT_MONTGOMERY||defined KGENMACRO_CONFIG_BIGINT_BARRETT))
#define KGEN_x101 (((KGEN_x61)||(!(KGEN_x91))))
#define KGEN_x100 ((defined KGENMACRO_CONFIG_BIGINT_CLASSICAL||defined KGENMACRO_CONFIG_BIGINT_MONTGOMERY||defined KGENMACRO_CONFIG_BIGINT_BARRETT||defined KGENMACRO_CONFIG_SSL_SKELETON_MODE))
#define KGEN_x93 ((defined KGENMACRO_CONFIG_SSL_PROT_LOW||defined KGENMACRO_CONFIG_SSL_PROT_MEDIUM||defined KGENMACRO_CONFIG_SSL_PROT_HIGH))
#define KGEN_x106 (((KGEN_x61)||(!(KGEN_x93))))
#define KGEN_x105 ((defined KGENMACRO_CONFIG_SSL_PROT_LOW||defined KGENMACRO_CONFIG_SSL_PROT_MEDIUM||defined KGENMACRO_CONFIG_SSL_PROT_HIGH||defined KGENMACRO_CONFIG_SSL_SKELETON_MODE))
#define KGEN_x103 ((defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0||defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0||defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0))
#define KGEN_x112 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32||(!(KGEN_x103))))
#define KGEN_x111 ((defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0||defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0||defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0||(KGEN_x84)))
#define KGEN_x122 ((!defined KGENMACRO_CONFIG_AXHTTPD))
#define KGEN_x123 ((defined KGENMACRO_CONFIG_HTTP_SESSION_CACHE_SIZE||(KGEN_x122)))
#define KGEN_x121 (((!defined KGENMACRO_CONFIG_HTTP_SESSION_CACHE_SIZE)||defined KGENMACRO_CONFIG_AXHTTPD))
#define KGEN_x118 (((!defined KGENMACRO_CONFIG_SSL_SERVER_ONLY)&&(KGEN_x61)))
#define KGEN_x132 ((!(KGEN_x118)))
#define KGEN_x133 ((defined KGENMACRO_CONFIG_X509_MAX_CA_CERTS||(KGEN_x132)))
#define KGEN_x131 (((!defined KGENMACRO_CONFIG_X509_MAX_CA_CERTS)||(KGEN_x118)))
#define KGEN_x130 ((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_PERL_BINDINGS))
#define KGEN_x139 ((!(KGEN_x130)))
#define KGEN_x137 (((!defined KGENMACRO_CONFIG_PERL_SAMPLES)||(KGEN_x130)))
#define KGEN_x149 (((!defined KGENMACRO_CONFIG_BIGINT_SLIDING_WINDOW)||(KGEN_x61)))
#define KGEN_x171 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&(KGEN_x149)&&(defined KGENMACRO_CONFIG_SSL_SKELETON_MODE||defined KGENMACRO_CONFIG_BIGINT_SLIDING_WINDOW)))
#define KGEN_x114 ((!defined KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT))
#define KGEN_x166 (((KGEN_x114)||defined KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_NAME))
#define KGEN_x165 ((defined KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT||(!defined KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_NAME)))
#define KGEN_x158 ((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_CSHARP_BINDINGS))
#define KGEN_x170 ((!(KGEN_x158)))
#define KGEN_x164 (((!defined KGENMACRO_CONFIG_CSHARP_SAMPLES)||(KGEN_x158)))
#define KGEN_x198 (((KGEN_x61)&&defined KGENMACRO_CONFIG_SSL_FULL_MODE&&(!((KGEN_x61)&&(!defined KGENMACRO_CONFIG_SSL_FULL_MODE)))))
#define KGEN_x200 ((!(KGEN_x198)))
#define KGEN_x203 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&((!defined KGENMACRO_CONFIG_SSL_HAS_PEM)||(KGEN_x198))&&(defined KGENMACRO_CONFIG_SSL_HAS_PEM||(KGEN_x200))))
#define KGEN_x185 ((!defined KGENMACRO_CONFIG_HTTP_HAS_IPV6))
#define KGEN_x181 ((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)))
#define KGEN_x190 ((!(KGEN_x181)))
#define KGEN_x218 ((!(defined KGENMACRO_CONFIG_CSHARP_BINDINGS||defined KGENMACRO_CONFIG_VBNET_BINDINGS)))
#define KGEN_x222 ((defined KGENMACRO_CONFIG_DOT_NET_FRAMEWORK_BASE||(KGEN_x218)))
#define KGEN_x217 ((defined KGENMACRO_CONFIG_CSHARP_BINDINGS||(!defined KGENMACRO_CONFIG_DOT_NET_FRAMEWORK_BASE)||defined KGENMACRO_CONFIG_VBNET_BINDINGS))
#define KGEN_x244 ((defined KGENMACRO_CONFIG_HTTP_VERBOSE||(!(defined KGENMACRO_CONFIG_AXHTTPD&&defined KGENMACRO_CONFIG_SSL_FULL_MODE))))
#define KGEN_x216 ((defined KGENMACRO_CONFIG_AXHTTPD&&defined KGENMACRO_CONFIG_SSL_FULL_MODE))
#define KGEN_x210 ((!defined KGENMACRO_CONFIG_HTTP_VERBOSE))
#define KGEN_x226 (((!defined KGENMACRO_CONFIG_BIGINT_SQUARE)||(KGEN_x61)))
#define KGEN_x251 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&(KGEN_x226)&&(defined KGENMACRO_CONFIG_SSL_SKELETON_MODE||defined KGENMACRO_CONFIG_BIGINT_SQUARE)))
#define KGEN_x232 ((!defined KGENMACRO_CONFIG_WIN32_USE_CRYPTO_LIB))
#define KGEN_x260 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32&&(defined KGENMACRO_CONFIG_PLATFORM_WIN32||(KGEN_x232))))
#define KGEN_x245 ((!defined KGENMACRO_CONFIG_PERFORMANCE_TESTING))
#define KGEN_x271 ((defined KGENMACRO_CONFIG_SSL_CERT_VERIFICATION&&(defined KGENMACRO_CONFIG_SSL_CERT_VERIFICATION||(KGEN_x245))))
#define KGEN_x193 ((!defined KGENMACRO_CONFIG_SSL_USE_DEFAULT_KEY))
#define KGEN_x194 (((KGEN_x193)&&(KGEN_x61)))
#define KGEN_x278 (((!(KGEN_x194))||defined KGENMACRO_CONFIG_SSL_PRIVATE_KEY_LOCATION))
#define KGEN_x274 (((!defined KGENMACRO_CONFIG_SSL_PRIVATE_KEY_LOCATION)||(KGEN_x194)))
#define KGEN_x266 ((!defined KGENMACRO_CONFIG_HTTP_ENABLE_DIFFERENT_USER))
#define KGEN_x290 (((KGEN_x193)&&defined KGENMACRO_CONFIG_SSL_HAS_PEM))
#define KGEN_x303 ((!(KGEN_x290)))
#define KGEN_x304 ((defined KGENMACRO_CONFIG_SSL_PRIVATE_KEY_PASSWORD||(KGEN_x303)))
#define KGEN_x302 (((!defined KGENMACRO_CONFIG_SSL_PRIVATE_KEY_PASSWORD)||(KGEN_x290)))
#define KGEN_x296 ((defined KGENMACRO_CONFIG_BINDINGS&&((!defined KGENMACRO_CONFIG_JAVA_BINDINGS)||defined KGENMACRO_CONFIG_BINDINGS)))
#define KGEN_x316 (((KGEN_x122)||defined KGENMACRO_CONFIG_HTTP_PORT))
#define KGEN_x315 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_PORT)))
#define KGEN_x311 ((!defined KGENMACRO_CONFIG_BIGINT_KARATSUBA))
#define KGEN_x341 ((defined KGENMACRO_CONFIG_BINDINGS&&(defined KGENMACRO_CONFIG_BINDINGS||(!defined KGENMACRO_CONFIG_CSHARP_BINDINGS))))
#define KGEN_x324 (((!defined KGENMACRO_CONFIG_HTTP_HAS_CGI)||(KGEN_x181)))
#define KGEN_x327 ((!defined KGENMACRO_CONFIG_SSL_TEST))
#define KGEN_x325 ((defined KGENMACRO_CONFIG_SSL_FULL_MODE&&(KGEN_x114)))
#define KGEN_x351 (((KGEN_x122)||defined KGENMACRO_CONFIG_HTTP_WEBROOT))
#define KGEN_x350 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_WEBROOT)))
#define KGEN_x366 ((defined KGENMACRO_CONFIG_BINDINGS&&(defined KGENMACRO_CONFIG_BINDINGS||(!defined KGENMACRO_CONFIG_VBNET_BINDINGS))))
#define KGEN_x370 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_DIRECTORIES)))
#define KGEN_x387 (((KGEN_x122)||defined KGENMACRO_CONFIG_HTTP_HTTPS_PORT))
#define KGEN_x386 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_HTTPS_PORT)))
#define KGEN_x286 (((KGEN_x61)&&defined KGENMACRO_CONFIG_BIGINT_KARATSUBA&&defined KGENMACRO_CONFIG_BIGINT_SQUARE))
#define KGEN_x395 (((!(KGEN_x286))||defined KGENMACRO_SQU_KARATSUBA_THRESH))
#define KGEN_x394 (((!defined KGENMACRO_SQU_KARATSUBA_THRESH)||(KGEN_x286)))
#define KGEN_x362 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32&&defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0))
#define KGEN_x400 (((!(KGEN_x362))||defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0_BASE))
#define KGEN_x399 (((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0_BASE)||(KGEN_x362)))
#define KGEN_x417 (((KGEN_x84)||(!defined KGENMACRO_CONFIG_USE_DEV_URANDOM)))
#define KGEN_x421 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32&&(KGEN_x417)&&(defined KGENMACRO_CONFIG_PLATFORM_WIN32||defined KGENMACRO_CONFIG_USE_DEV_URANDOM)))
#define KGEN_x398 ((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&defined KGENMACRO_CONFIG_HTTP_HAS_CGI))
#define KGEN_x406 ((!(KGEN_x398)))
#define KGEN_x404 (((!defined KGENMACRO_CONFIG_HTTP_ENABLE_LUA)||(KGEN_x398)))
#define KGEN_x434 ((defined KGENMACRO_CONFIG_AXHTTPD&&(defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_STATIC_BUILD))))
#define KGEN_x431 ((!defined KGENMACRO_CONFIG_LUA_BINDINGS))
#define KGEN_x457 (((!(defined KGENMACRO_CONFIG_BINDINGS&&(!defined KGENMACRO_CONFIG_PLATFORM_WIN32)))&&(KGEN_x431)))
#define KGEN_x424 ((defined KGENMACRO_CONFIG_BINDINGS&&(KGEN_x84)))
#define KGEN_x460 (((KGEN_x61)||(KGEN_x193)))
#define KGEN_x464 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&(KGEN_x460)&&(defined KGENMACRO_CONFIG_SSL_SKELETON_MODE||defined KGENMACRO_CONFIG_SSL_USE_DEFAULT_KEY)))
#define KGEN_x353 (((KGEN_x61)&&defined KGENMACRO_CONFIG_BIGINT_KARATSUBA))
#define KGEN_x452 (((!(KGEN_x353))||defined KGENMACRO_MUL_KARATSUBA_THRESH))
#define KGEN_x451 (((!defined KGENMACRO_MUL_KARATSUBA_THRESH)||(KGEN_x353)))
#define KGEN_x469 (((KGEN_x431)||defined KGENMACRO_CONFIG_LUA_CORE))
#define KGEN_x468 ((defined KGENMACRO_CONFIG_LUA_BINDINGS||(!defined KGENMACRO_CONFIG_LUA_CORE)))
#define KGEN_x477 (((!defined KGENMACRO_CONFIG_JAVA_BINDINGS)||defined KGENMACRO_CONFIG_JAVA_HOME))
#define KGEN_x476 ((defined KGENMACRO_CONFIG_JAVA_BINDINGS||(!defined KGENMACRO_CONFIG_JAVA_HOME)))
#define KGEN_x423 ((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&defined KGENMACRO_CONFIG_HTTP_ENABLE_LUA))
#define KGEN_x430 ((!(KGEN_x423)))
#define KGEN_x486 (((KGEN_x430)||defined KGENMACRO_CONFIG_HTTP_LUA_PREFIX))
#define KGEN_x485 (((!defined KGENMACRO_CONFIG_HTTP_LUA_PREFIX)||(KGEN_x423)))
#define KGEN_x482 (((!defined KGENMACRO_CONFIG_BIGINT_CRT)||(KGEN_x61)))
#define KGEN_x506 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&(KGEN_x482)&&(defined KGENMACRO_CONFIG_SSL_SKELETON_MODE||defined KGENMACRO_CONFIG_BIGINT_CRT)))
#define KGEN_x484 ((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_LUA_BINDINGS))
#define KGEN_x498 ((!(KGEN_x484)))
#define KGEN_x496 (((!defined KGENMACRO_CONFIG_LUA_SAMPLES)||(KGEN_x484)))
#define KGEN_x517 (((KGEN_x114)||defined KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME))
#define KGEN_x514 ((defined KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT||(!defined KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME)))
#define KGEN_x528 (((KGEN_x114)||defined KGENMACRO_CONFIG_SSL_X509_COMMON_NAME))
#define KGEN_x527 ((defined KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT||(!defined KGENMACRO_CONFIG_SSL_X509_COMMON_NAME)))
#define KGEN_x547 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_HAS_AUTHORIZATION)))
#define KGEN_x540 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32||defined KGENMACRO_PREFIX))
#define KGEN_x539 (((KGEN_x84)||(!defined KGENMACRO_PREFIX)))
#define KGEN_x560 ((defined KGENMACRO_CONFIG_SAMPLES||(!defined KGENMACRO_CONFIG_C_SAMPLES)))
#define KGEN_x538 ((!defined KGENMACRO_CONFIG_SAMPLES))
#define KGEN_x556 (((KGEN_x406)||defined KGENMACRO_CONFIG_HTTP_CGI_LAUNCHER))
#define KGEN_x555 (((!defined KGENMACRO_CONFIG_HTTP_CGI_LAUNCHER)||(KGEN_x398)))
#define KGEN_x566 (((KGEN_x406)||defined KGENMACRO_CONFIG_HTTP_CGI_EXTENSIONS))
#define KGEN_x563 (((!defined KGENMACRO_CONFIG_HTTP_CGI_EXTENSIONS)||(KGEN_x398)))
#define KGEN_x571 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE||defined KGENMACRO_CONFIG_SSL_EXPIRY_TIME))
#define KGEN_x570 (((!defined KGENMACRO_CONFIG_SSL_EXPIRY_TIME)||(KGEN_x61)))
#define KGEN_x554 ((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_JAVA_BINDINGS))
#define KGEN_x573 ((!(KGEN_x554)))
#define KGEN_x568 (((!defined KGENMACRO_CONFIG_JAVA_SAMPLES)||(KGEN_x554)))
#define KGEN_x445 ((defined KGENMACRO_CONFIG_PERL_BINDINGS&&defined KGENMACRO_CONFIG_PLATFORM_WIN32))
#define KGEN_x454 ((!(KGEN_x445)))
#define KGEN_x581 (((KGEN_x454)||defined KGENMACRO_CONFIG_PERL_LIB))
#define KGEN_x580 (((!defined KGENMACRO_CONFIG_PERL_LIB)||(KGEN_x445)))
#define KGEN_x590 (((!(defined KGENMACRO_CONFIG_PLATFORM_WIN32&&defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0))||defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0_BASE))
#define KGEN_x230 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32&&defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0))
#define KGEN_x589 (((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0_BASE)||(KGEN_x230)))
#define KGEN_x579 ((defined KGENMACRO_CONFIG_AXHTTPD&&defined KGENMACRO_CONFIG_HTTP_ENABLE_DIFFERENT_USER))
#define KGEN_x596 ((!(KGEN_x579)))
#define KGEN_x597 ((defined KGENMACRO_CONFIG_HTTP_USER||(KGEN_x596)))
#define KGEN_x595 (((!defined KGENMACRO_CONFIG_HTTP_USER)||(KGEN_x579)))
#define KGEN_x593 ((!defined KGENMACRO_CONFIG_HTTP_IS_DAEMON))
#define KGEN_x615 (((!(defined KGENMACRO_CONFIG_AXHTTPD&&(!defined KGENMACRO_CONFIG_PLATFORM_WIN32)))&&(KGEN_x593)))
#define KGEN_x602 ((!defined KGENMACRO_CONFIG_HTTP_BUILD_LUA))
#define KGEN_x625 ((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&defined KGENMACRO_CONFIG_HTTP_ENABLE_LUA&&((KGEN_x602)||(KGEN_x423))))
#define KGEN_x621 (((KGEN_x122)||defined KGENMACRO_CONFIG_HTTP_TIMEOUT))
#define KGEN_x617 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_TIMEOUT)))
#define KGEN_x629 (((!(defined KGENMACRO_CONFIG_PERL_BINDINGS&&defined KGENMACRO_CONFIG_PLATFORM_WIN32))||defined KGENMACRO_CONFIG_PERL_CORE))
#define KGEN_x628 (((!defined KGENMACRO_CONFIG_PERL_CORE)||(KGEN_x445)))
#define KGEN_x649 ((!((!defined KGENMACRO_CONFIG_SSL_SKELETON_MODE)&&(!defined KGENMACRO_CONFIG_DEBUG))))
#define KGEN_x650 (((KGEN_x61)&&defined KGENMACRO_CONFIG_DEBUG&&(KGEN_x649)))
#define KGEN_x655 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&((!defined KGENMACRO_CONFIG_BIGINT_CHECK_ON)||(KGEN_x650))&&(defined KGENMACRO_CONFIG_BIGINT_CHECK_ON||(!(KGEN_x650)))))
#define KGEN_x624 ((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_VBNET_BINDINGS))
#define KGEN_x638 ((!(KGEN_x624)))
#define KGEN_x636 (((!defined KGENMACRO_CONFIG_VBNET_SAMPLES)||(KGEN_x624)))
#define KGEN_x664 ((defined KGENMACRO_CONFIG_BINDINGS&&(defined KGENMACRO_CONFIG_BINDINGS||(!defined KGENMACRO_CONFIG_PERL_BINDINGS))))
#define KGEN_x414 (((!defined KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT)&&(!defined KGENMACRO_CONFIG_SSL_USE_DEFAULT_KEY)&&(KGEN_x61)))
#define KGEN_x658 (((!(KGEN_x414))||defined KGENMACRO_CONFIG_SSL_X509_CERT_LOCATION))
#define KGEN_x648 (((!defined KGENMACRO_CONFIG_SSL_X509_CERT_LOCATION)||(KGEN_x414)))
#define KGEN_x632 ((!defined KGENMACRO_CONFIG_DEBUG))
#define KGEN_x643 (((KGEN_x84)&&(KGEN_x632)))
#define KGEN_x662 ((!(KGEN_x643)))
#define KGEN_x646 (((!defined KGENMACRO_CONFIG_STRIP_UNWANTED_SECTIONS)||(KGEN_x643)))
#define KGEN_x698 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&((!defined KGENMACRO_CONFIG_SSL_USE_PKCS12)||(KGEN_x198))&&((!(KGEN_x198))||defined KGENMACRO_CONFIG_SSL_USE_PKCS12)))
#define KGEN_x687 (((!(defined KGENMACRO_CONFIG_PLATFORM_WIN32&&defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0))||defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0_BASE))
#define KGEN_x500 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32&&defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0))
#define KGEN_x686 (((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0_BASE)||(KGEN_x500)))
#if (((KGEN_x617)&&(KGEN_x621)))
#ifdef KGENMACRO_CONFIG_HTTP_TIMEOUT
#define CONFIG_HTTP_TIMEOUT 300
#else
#define CONFIG_HTTP_TIMEOUT 0
#endif
#endif
#if (((KGEN_x165)&&(KGEN_x166)))
#ifdef KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_NAME
#define CONFIG_SSL_X509_ORGANIZATION_NAME "X"
#else
#define CONFIG_SSL_X509_ORGANIZATION_NAME ""
#endif
#endif
#if (((KGEN_x50)||(KGEN_x52))) && (((KGEN_x50)||(KGEN_x55))) && (((KGEN_x50)||(KGEN_x58))) && (((KGEN_x50)||(KGEN_x61)))
#ifdef KGENMACRO_CONFIG_SSL_SERVER_ONLY
#define CONFIG_SSL_SERVER_ONLY 1
#else
#undef CONFIG_SSL_SERVER_ONLY
#endif
#endif
#if (((KGEN_x476)&&(KGEN_x477)))
#ifdef KGENMACRO_CONFIG_JAVA_HOME
#define CONFIG_JAVA_HOME "/usr/lib/jvm/java-7-openjdk-amd64"
#else
#define CONFIG_JAVA_HOME ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SSL_FULL_MODE&&(KGEN_x114)&&((KGEN_x327)||(KGEN_x325)))||((!(KGEN_x325))&&(KGEN_x327))))
#ifdef KGENMACRO_CONFIG_SSL_TEST
#define CONFIG_SSL_TEST 1
#else
#undef CONFIG_SSL_TEST
#endif
#endif
#if (((KGEN_x41)||(KGEN_x43))) && (((KGEN_x41)||(KGEN_x46)))
#ifdef KGENMACRO_CONFIG_SSL_PROT_LOW
#define CONFIG_SSL_PROT_LOW 1
#else
#undef CONFIG_SSL_PROT_LOW
#endif
#endif
#if (((KGEN_x217)&&(KGEN_x222)))
#ifdef KGENMACRO_CONFIG_DOT_NET_FRAMEWORK_BASE
#define CONFIG_DOT_NET_FRAMEWORK_BASE "c:\\WINDOWS\\Microsoft.NET\\Framework\\v2.0.50727"
#else
#define CONFIG_DOT_NET_FRAMEWORK_BASE ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x370))||((KGEN_x122)&&(KGEN_x370)&&((KGEN_x122)||defined KGENMACRO_CONFIG_HTTP_DIRECTORIES))))
#ifdef KGENMACRO_CONFIG_HTTP_DIRECTORIES
#define CONFIG_HTTP_DIRECTORIES 1
#else
#undef CONFIG_HTTP_DIRECTORIES
#endif
#endif
#if (((KGEN_x628)&&(KGEN_x629)))
#ifdef KGENMACRO_CONFIG_PERL_CORE
#define CONFIG_PERL_CORE "c:\\perl\\lib\\CORE"
#else
#define CONFIG_PERL_CORE ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_VBNET_BINDINGS&&(KGEN_x636))||((KGEN_x638)&&(KGEN_x636)&&(defined KGENMACRO_CONFIG_VBNET_SAMPLES||(KGEN_x638)))))
#ifdef KGENMACRO_CONFIG_VBNET_SAMPLES
#define CONFIG_VBNET_SAMPLES 1
#else
#undef CONFIG_VBNET_SAMPLES
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_CSHARP_BINDINGS&&(KGEN_x164))||((KGEN_x170)&&(KGEN_x164)&&(defined KGENMACRO_CONFIG_CSHARP_SAMPLES||(KGEN_x170)))))
#ifdef KGENMACRO_CONFIG_CSHARP_SAMPLES
#define CONFIG_CSHARP_SAMPLES 1
#else
#undef CONFIG_CSHARP_SAMPLES
#endif
#endif
#if (((KGEN_x570)&&(KGEN_x571)))
#ifdef KGENMACRO_CONFIG_SSL_EXPIRY_TIME
#define CONFIG_SSL_EXPIRY_TIME 24
#else
#define CONFIG_SSL_EXPIRY_TIME 0
#endif
#endif
#if (((KGEN_x664)||((!defined KGENMACRO_CONFIG_BINDINGS)&&(!defined KGENMACRO_CONFIG_PERL_BINDINGS))))
#ifdef KGENMACRO_CONFIG_PERL_BINDINGS
#define CONFIG_PERL_BINDINGS 1
#else
#undef CONFIG_PERL_BINDINGS
#endif
#endif
#ifdef KGENMACRO_CONFIG_PLATFORM_WIN32
#define CONFIG_PLATFORM_WIN32 1
#else
#undef CONFIG_PLATFORM_WIN32
#endif
#if (defined KGENMACRO_CONFIG_SSL_MAX_CERTS)
#ifdef KGENMACRO_CONFIG_SSL_MAX_CERTS
#define CONFIG_SSL_MAX_CERTS 3
#else
#define CONFIG_SSL_MAX_CERTS 0
#endif
#endif
#if ((((KGEN_x84)&&((!defined KGENMACRO_CONFIG_AXTLSWRAP)||(KGEN_x84)))||(defined KGENMACRO_CONFIG_PLATFORM_WIN32&&(!defined KGENMACRO_CONFIG_AXTLSWRAP))))
#ifdef KGENMACRO_CONFIG_AXTLSWRAP
#define CONFIG_AXTLSWRAP 1
#else
#undef CONFIG_AXTLSWRAP
#endif
#endif
#if (defined KGENMACRO_CONFIG_EXTRA_CFLAGS_OPTIONS)
#ifdef KGENMACRO_CONFIG_EXTRA_CFLAGS_OPTIONS
#define CONFIG_EXTRA_CFLAGS_OPTIONS "X"
#else
#define CONFIG_EXTRA_CFLAGS_OPTIONS ""
#endif
#endif
#ifdef KGENMACRO_CONFIG_BIGINT_BARRETT
#define CONFIG_BIGINT_BARRETT 1
#else
#undef CONFIG_BIGINT_BARRETT
#endif
#ifdef KGENMACRO_UNAME_RELEASE
#define UNAME_RELEASE "5.4.0-135-generic"
#else
#define UNAME_RELEASE ""
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&(KGEN_x560))||((KGEN_x538)&&(KGEN_x560)&&(defined KGENMACRO_CONFIG_C_SAMPLES||(KGEN_x538)))))
#ifdef KGENMACRO_CONFIG_C_SAMPLES
#define CONFIG_C_SAMPLES 1
#else
#undef CONFIG_C_SAMPLES
#endif
#endif
#if (defined KGENMACRO_HAVE_DOT_CONFIG)
#ifdef KGENMACRO_HAVE_DOT_CONFIG
#define HAVE_DOT_CONFIG 1
#else
#undef HAVE_DOT_CONFIG
#endif
#endif
#if (((KGEN_x32)||(KGEN_x34))) && (((KGEN_x32)||(KGEN_x37)))
#ifdef KGENMACRO_CONFIG_BIGINT_CLASSICAL
#define CONFIG_BIGINT_CLASSICAL 1
#else
#undef CONFIG_BIGINT_CLASSICAL
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_JAVA_BINDINGS&&(KGEN_x568))||((KGEN_x573)&&(KGEN_x568)&&(defined KGENMACRO_CONFIG_JAVA_SAMPLES||(KGEN_x573)))))
#ifdef KGENMACRO_CONFIG_JAVA_SAMPLES
#define CONFIG_JAVA_SAMPLES 1
#else
#undef CONFIG_JAVA_SAMPLES
#endif
#endif
#if (((KGEN_x451)&&(KGEN_x452)))
#ifdef KGENMACRO_MUL_KARATSUBA_THRESH
#define MUL_KARATSUBA_THRESH 20
#else
#define MUL_KARATSUBA_THRESH 0
#endif
#endif
#ifdef KGENMACRO_CONFIG_DEBUG
#define CONFIG_DEBUG 1
#else
#undef CONFIG_DEBUG
#endif
#if (((KGEN_x399)&&(KGEN_x400)))
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_10_0_BASE
#define CONFIG_VISUAL_STUDIO_10_0_BASE "c:\\Program Files\\Microsoft Visual Studio 10.0"
#else
#define CONFIG_VISUAL_STUDIO_10_0_BASE ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_LUA_BINDINGS&&(KGEN_x496))||((KGEN_x498)&&(KGEN_x496)&&(defined KGENMACRO_CONFIG_LUA_SAMPLES||(KGEN_x498)))))
#ifdef KGENMACRO_CONFIG_LUA_SAMPLES
#define CONFIG_LUA_SAMPLES 1
#else
#undef CONFIG_LUA_SAMPLES
#endif
#endif
#if (((!defined KGENMACRO_CONFIG_SSL_PROT_MEDIUM)||(!defined KGENMACRO_CONFIG_SSL_PROT_HIGH)))
#ifdef KGENMACRO_CONFIG_SSL_PROT_MEDIUM
#define CONFIG_SSL_PROT_MEDIUM 1
#else
#undef CONFIG_SSL_PROT_MEDIUM
#endif
#endif
#ifdef KGENMACRO_CONFIG_AXHTTPD
#define CONFIG_AXHTTPD 1
#else
#undef CONFIG_AXHTTPD
#endif
#ifdef KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT
#define CONFIG_SSL_GENERATE_X509_CERT 1
#else
#undef CONFIG_SSL_GENERATE_X509_CERT
#endif
#if ((((KGEN_x61)&&((KGEN_x61)||(!defined KGENMACRO_CONFIG_SSL_USE_PKCS12)))||(KGEN_x698)))
#ifdef KGENMACRO_CONFIG_SSL_USE_PKCS12
#define CONFIG_SSL_USE_PKCS12 1
#else
#undef CONFIG_SSL_USE_PKCS12
#endif
#endif
#if (((KGEN_x131)&&(KGEN_x133)))
#ifdef KGENMACRO_CONFIG_X509_MAX_CA_CERTS
#define CONFIG_X509_MAX_CA_CERTS 150
#else
#define CONFIG_X509_MAX_CA_CERTS 0
#endif
#endif
#if (((KGEN_x686)&&(KGEN_x687)))
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_8_0_BASE
#define CONFIG_VISUAL_STUDIO_8_0_BASE "c:\\Program Files\\Microsoft Visual Studio 8"
#else
#define CONFIG_VISUAL_STUDIO_8_0_BASE ""
#endif
#endif
#if (((KGEN_x539)&&(KGEN_x540)))
#ifdef KGENMACRO_PREFIX
#define PREFIX "/usr/local"
#else
#define PREFIX ""
#endif
#endif
#if (((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0)||(!defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0)))
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_8_0
#define CONFIG_VISUAL_STUDIO_8_0 1
#else
#undef CONFIG_VISUAL_STUDIO_8_0
#endif
#endif
#if (((KGEN_x648)&&(KGEN_x658)))
#ifdef KGENMACRO_CONFIG_SSL_X509_CERT_LOCATION
#define CONFIG_SSL_X509_CERT_LOCATION "X"
#else
#define CONFIG_SSL_X509_CERT_LOCATION ""
#endif
#endif
#if (((KGEN_x366)||((!defined KGENMACRO_CONFIG_BINDINGS)&&(!defined KGENMACRO_CONFIG_VBNET_BINDINGS))))
#ifdef KGENMACRO_CONFIG_VBNET_BINDINGS
#define CONFIG_VBNET_BINDINGS 1
#else
#undef CONFIG_VBNET_BINDINGS
#endif
#endif
#if (((KGEN_x58)||(KGEN_x61)))
#ifdef KGENMACRO_CONFIG_SSL_FULL_MODE
#define CONFIG_SSL_FULL_MODE 1
#else
#undef CONFIG_SSL_FULL_MODE
#endif
#endif
#if (((!defined KGENMACRO_CONFIG_BIGINT_MONTGOMERY)||(!defined KGENMACRO_CONFIG_BIGINT_BARRETT)))
#ifdef KGENMACRO_CONFIG_BIGINT_MONTGOMERY
#define CONFIG_BIGINT_MONTGOMERY 1
#else
#undef CONFIG_BIGINT_MONTGOMERY
#endif
#endif
#if (((KGEN_x315)&&(KGEN_x316)))
#ifdef KGENMACRO_CONFIG_HTTP_PORT
#define CONFIG_HTTP_PORT 80
#else
#define CONFIG_HTTP_PORT 0
#endif
#endif
#if (((KGEN_x386)&&(KGEN_x387)))
#ifdef KGENMACRO_CONFIG_HTTP_HTTPS_PORT
#define CONFIG_HTTP_HTTPS_PORT 443
#else
#define CONFIG_HTTP_HTTPS_PORT 0
#endif
#endif
#ifdef KGENMACRO_CONFIG_SSL_CTX_MUTEXING
#define CONFIG_SSL_CTX_MUTEXING 1
#else
#undef CONFIG_SSL_CTX_MUTEXING
#endif
#if (((KGEN_x341)||((!defined KGENMACRO_CONFIG_BINDINGS)&&(!defined KGENMACRO_CONFIG_CSHARP_BINDINGS))))
#ifdef KGENMACRO_CONFIG_CSHARP_BINDINGS
#define CONFIG_CSHARP_BINDINGS 1
#else
#undef CONFIG_CSHARP_BINDINGS
#endif
#endif
#if (((KGEN_x485)&&(KGEN_x486)))
#ifdef KGENMACRO_CONFIG_HTTP_LUA_PREFIX
#define CONFIG_HTTP_LUA_PREFIX "/usr"
#else
#define CONFIG_HTTP_LUA_PREFIX ""
#endif
#endif
#ifdef KGENMACRO_CONFIG_SSL_SKELETON_MODE
#define CONFIG_SSL_SKELETON_MODE 1
#else
#undef CONFIG_SSL_SKELETON_MODE
#endif
#if ((((KGEN_x61)&&(KGEN_x226))||(KGEN_x251)))
#ifdef KGENMACRO_CONFIG_BIGINT_SQUARE
#define CONFIG_BIGINT_SQUARE 1
#else
#undef CONFIG_BIGINT_SQUARE
#endif
#endif
#if ((((KGEN_x84)&&(KGEN_x417))||(KGEN_x421)))
#ifdef KGENMACRO_CONFIG_USE_DEV_URANDOM
#define CONFIG_USE_DEV_URANDOM 1
#else
#undef CONFIG_USE_DEV_URANDOM
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_PERL_BINDINGS&&(KGEN_x137))||((KGEN_x139)&&(KGEN_x137)&&(defined KGENMACRO_CONFIG_PERL_SAMPLES||(KGEN_x139)))))
#ifdef KGENMACRO_CONFIG_PERL_SAMPLES
#define CONFIG_PERL_SAMPLES 1
#else
#undef CONFIG_PERL_SAMPLES
#endif
#endif
#if (((KGEN_x625)||((!(KGEN_x423))&&(KGEN_x602))))
#ifdef KGENMACRO_CONFIG_HTTP_BUILD_LUA
#define CONFIG_HTTP_BUILD_LUA 1
#else
#undef CONFIG_HTTP_BUILD_LUA
#endif
#endif
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_10_0
#define CONFIG_VISUAL_STUDIO_10_0 1
#else
#undef CONFIG_VISUAL_STUDIO_10_0
#endif
#if (((KGEN_x271)||((!defined KGENMACRO_CONFIG_SSL_CERT_VERIFICATION)&&(KGEN_x245))))
#ifdef KGENMACRO_CONFIG_PERFORMANCE_TESTING
#define CONFIG_PERFORMANCE_TESTING 1
#else
#undef CONFIG_PERFORMANCE_TESTING
#endif
#endif
#if (((KGEN_x394)&&(KGEN_x395)))
#ifdef KGENMACRO_SQU_KARATSUBA_THRESH
#define SQU_KARATSUBA_THRESH 40
#else
#define SQU_KARATSUBA_THRESH 0
#endif
#endif
#if (defined KGENMACRO_CONFIG_EXTRA_LDFLAGS_OPTIONS)
#ifdef KGENMACRO_CONFIG_EXTRA_LDFLAGS_OPTIONS
#define CONFIG_EXTRA_LDFLAGS_OPTIONS "X"
#else
#define CONFIG_EXTRA_LDFLAGS_OPTIONS ""
#endif
#endif
#if ((((KGEN_x84)&&(KGEN_x632)&&(KGEN_x646))||((KGEN_x662)&&(KGEN_x646)&&(defined KGENMACRO_CONFIG_STRIP_UNWANTED_SECTIONS||(KGEN_x662)))))
#ifdef KGENMACRO_CONFIG_STRIP_UNWANTED_SECTIONS
#define CONFIG_STRIP_UNWANTED_SECTIONS 1
#else
#undef CONFIG_STRIP_UNWANTED_SECTIONS
#endif
#endif
#if (((KGEN_x55)||(KGEN_x58))) && (((KGEN_x55)||(KGEN_x61)))
#ifdef KGENMACRO_CONFIG_SSL_ENABLE_CLIENT
#define CONFIG_SSL_ENABLE_CLIENT 1
#else
#undef CONFIG_SSL_ENABLE_CLIENT
#endif
#endif
#if ((((KGEN_x61)&&(KGEN_x460))||(KGEN_x464)))
#ifdef KGENMACRO_CONFIG_SSL_USE_DEFAULT_KEY
#define CONFIG_SSL_USE_DEFAULT_KEY 1
#else
#undef CONFIG_SSL_USE_DEFAULT_KEY
#endif
#endif
#if (((KGEN_x52)||(KGEN_x55))) && (((KGEN_x52)||(KGEN_x58))) && (((KGEN_x52)||(KGEN_x61)))
#ifdef KGENMACRO_CONFIG_SSL_CERT_VERIFICATION
#define CONFIG_SSL_CERT_VERIFICATION 1
#else
#undef CONFIG_SSL_CERT_VERIFICATION
#endif
#endif
#if (((KGEN_x350)&&(KGEN_x351)))
#ifdef KGENMACRO_CONFIG_HTTP_WEBROOT
#define CONFIG_HTTP_WEBROOT "..\\www"
#else
#define CONFIG_HTTP_WEBROOT ""
#endif
#endif
#if (((KGEN_x434)||((!defined KGENMACRO_CONFIG_AXHTTPD)&&(!defined KGENMACRO_CONFIG_HTTP_STATIC_BUILD))))
#ifdef KGENMACRO_CONFIG_HTTP_STATIC_BUILD
#define CONFIG_HTTP_STATIC_BUILD 1
#else
#undef CONFIG_HTTP_STATIC_BUILD
#endif
#endif
#if (((KGEN_x121)&&(KGEN_x123)))
#ifdef KGENMACRO_CONFIG_HTTP_SESSION_CACHE_SIZE
#define CONFIG_HTTP_SESSION_CACHE_SIZE 5
#else
#define CONFIG_HTTP_SESSION_CACHE_SIZE 0
#endif
#endif
#if (((KGEN_x563)&&(KGEN_x566)))
#ifdef KGENMACRO_CONFIG_HTTP_CGI_EXTENSIONS
#define CONFIG_HTTP_CGI_EXTENSIONS ".lua,.lp,.php"
#else
#define CONFIG_HTTP_CGI_EXTENSIONS ""
#endif
#endif
#ifdef KGENMACRO_CONFIG_OPENSSL_COMPATIBLE
#define CONFIG_OPENSSL_COMPATIBLE 1
#else
#undef CONFIG_OPENSSL_COMPATIBLE
#endif
#if ((((KGEN_x61)&&(KGEN_x149))||(KGEN_x171)))
#ifdef KGENMACRO_CONFIG_BIGINT_SLIDING_WINDOW
#define CONFIG_BIGINT_SLIDING_WINDOW 1
#else
#undef CONFIG_BIGINT_SLIDING_WINDOW
#endif
#endif
#if (((KGEN_x70)||(KGEN_x72))) && (((KGEN_x70)||(KGEN_x75)))
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_7_0
#define CONFIG_VISUAL_STUDIO_7_0 1
#else
#undef CONFIG_VISUAL_STUDIO_7_0
#endif
#endif
#if ((((KGEN_x61)&&((KGEN_x311)||(KGEN_x61)))||(defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&(KGEN_x311))))
#ifdef KGENMACRO_CONFIG_BIGINT_KARATSUBA
#define CONFIG_BIGINT_KARATSUBA 1
#else
#undef CONFIG_BIGINT_KARATSUBA
#endif
#endif
#if ((((KGEN_x61)&&(KGEN_x482))||(KGEN_x506)))
#ifdef KGENMACRO_CONFIG_BIGINT_CRT
#define CONFIG_BIGINT_CRT 1
#else
#undef CONFIG_BIGINT_CRT
#endif
#endif
#if (((KGEN_x595)&&(KGEN_x597)))
#ifdef KGENMACRO_CONFIG_HTTP_USER
#define CONFIG_HTTP_USER "nobody"
#else
#define CONFIG_HTTP_USER ""
#endif
#endif
#if (((KGEN_x468)&&(KGEN_x469)))
#ifdef KGENMACRO_CONFIG_LUA_CORE
#define CONFIG_LUA_CORE "/usr/local"
#else
#define CONFIG_LUA_CORE ""
#endif
#endif
#if (((KGEN_x589)&&(KGEN_x590)))
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_7_0_BASE
#define CONFIG_VISUAL_STUDIO_7_0_BASE "c:\\Program Files\\Microsoft Visual Studio .NET 2003"
#else
#define CONFIG_VISUAL_STUDIO_7_0_BASE ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&(KGEN_x324))||((KGEN_x190)&&(KGEN_x324)&&((KGEN_x190)||defined KGENMACRO_CONFIG_HTTP_HAS_CGI))))
#ifdef KGENMACRO_CONFIG_HTTP_HAS_CGI
#define CONFIG_HTTP_HAS_CGI 1
#else
#undef CONFIG_HTTP_HAS_CGI
#endif
#endif
#if (((KGEN_x580)&&(KGEN_x581)))
#ifdef KGENMACRO_CONFIG_PERL_LIB
#define CONFIG_PERL_LIB "perl58.lib"
#else
#define CONFIG_PERL_LIB ""
#endif
#endif
#if (((KGEN_x23)||(KGEN_x25))) && (((KGEN_x23)||(KGEN_x28)))
#ifdef KGENMACRO_CONFIG_INTEGER_32BIT
#define CONFIG_INTEGER_32BIT 1
#else
#undef CONFIG_INTEGER_32BIT
#endif
#endif
#ifdef KGENMACRO_CONFIG_BINDINGS
#define CONFIG_BINDINGS 1
#else
#undef CONFIG_BINDINGS
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&((KGEN_x185)||(KGEN_x181)))||((KGEN_x190)&&(KGEN_x185))))
#ifdef KGENMACRO_CONFIG_HTTP_HAS_IPV6
#define CONFIG_HTTP_HAS_IPV6 1
#else
#undef CONFIG_HTTP_HAS_IPV6
#endif
#endif
#if (((!defined KGENMACRO_CONFIG_PLATFORM_CYGWIN)||(KGEN_x84)))
#ifdef KGENMACRO_CONFIG_PLATFORM_CYGWIN
#define CONFIG_PLATFORM_CYGWIN 1
#else
#undef CONFIG_PLATFORM_CYGWIN
#endif
#endif
#if (((KGEN_x274)&&(KGEN_x278)))
#ifdef KGENMACRO_CONFIG_SSL_PRIVATE_KEY_LOCATION
#define CONFIG_SSL_PRIVATE_KEY_LOCATION "X"
#else
#define CONFIG_SSL_PRIVATE_KEY_LOCATION ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_BINDINGS&&(KGEN_x84)&&((KGEN_x431)||(KGEN_x424)))||(KGEN_x457)))
#ifdef KGENMACRO_CONFIG_LUA_BINDINGS
#define CONFIG_LUA_BINDINGS 1
#else
#undef CONFIG_LUA_BINDINGS
#endif
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x547))||((KGEN_x122)&&(KGEN_x547)&&((KGEN_x122)||defined KGENMACRO_CONFIG_HTTP_HAS_AUTHORIZATION))))
#ifdef KGENMACRO_CONFIG_HTTP_HAS_AUTHORIZATION
#define CONFIG_HTTP_HAS_AUTHORIZATION 1
#else
#undef CONFIG_HTTP_HAS_AUTHORIZATION
#endif
#endif
#ifdef KGENMACRO_CONFIG_INTEGER_8BIT
#define CONFIG_INTEGER_8BIT 1
#else
#undef CONFIG_INTEGER_8BIT
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&defined KGENMACRO_CONFIG_HTTP_HAS_CGI&&(KGEN_x404))||((KGEN_x406)&&(KGEN_x404)&&(defined KGENMACRO_CONFIG_HTTP_ENABLE_LUA||(KGEN_x406)))))
#ifdef KGENMACRO_CONFIG_HTTP_ENABLE_LUA
#define CONFIG_HTTP_ENABLE_LUA 1
#else
#undef CONFIG_HTTP_ENABLE_LUA
#endif
#endif
#if (((KGEN_x296)||((!defined KGENMACRO_CONFIG_BINDINGS)&&(!defined KGENMACRO_CONFIG_JAVA_BINDINGS))))
#ifdef KGENMACRO_CONFIG_JAVA_BINDINGS
#define CONFIG_JAVA_BINDINGS 1
#else
#undef CONFIG_JAVA_BINDINGS
#endif
#endif
#if (((KGEN_x514)&&(KGEN_x517)))
#ifdef KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME
#define CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME "X"
#else
#define CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&((KGEN_x266)||(KGEN_x181)))||((KGEN_x190)&&(KGEN_x266))))
#ifdef KGENMACRO_CONFIG_HTTP_ENABLE_DIFFERENT_USER
#define CONFIG_HTTP_ENABLE_DIFFERENT_USER 1
#else
#undef CONFIG_HTTP_ENABLE_DIFFERENT_USER
#endif
#endif
#if ((((KGEN_x61)&&((!defined KGENMACRO_CONFIG_BIGINT_CHECK_ON)||(KGEN_x61)))||(KGEN_x655)))
#ifdef KGENMACRO_CONFIG_BIGINT_CHECK_ON
#define CONFIG_BIGINT_CHECK_ON 1
#else
#undef CONFIG_BIGINT_CHECK_ON
#endif
#endif
#if (((!defined KGENMACRO_CONFIG_INTEGER_16BIT)||(!defined KGENMACRO_CONFIG_INTEGER_8BIT)))
#ifdef KGENMACRO_CONFIG_INTEGER_16BIT
#define CONFIG_INTEGER_16BIT 1
#else
#undef CONFIG_INTEGER_16BIT
#endif
#endif
#ifdef KGENMACRO_CONFIG_SAMPLES
#define CONFIG_SAMPLES 1
#else
#undef CONFIG_SAMPLES
#endif
#if (((KGEN_x527)&&(KGEN_x528)))
#ifdef KGENMACRO_CONFIG_SSL_X509_COMMON_NAME
#define CONFIG_SSL_X509_COMMON_NAME "X"
#else
#define CONFIG_SSL_X509_COMMON_NAME ""
#endif
#endif
#if (((KGEN_x79)||(KGEN_x81))) && (((KGEN_x79)||(KGEN_x84)))
#ifdef KGENMACRO_CONFIG_PLATFORM_LINUX
#define CONFIG_PLATFORM_LINUX 1
#else
#undef CONFIG_PLATFORM_LINUX
#endif
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&((KGEN_x593)||(KGEN_x181)))||(KGEN_x615)))
#ifdef KGENMACRO_CONFIG_HTTP_IS_DAEMON
#define CONFIG_HTTP_IS_DAEMON 1
#else
#undef CONFIG_HTTP_IS_DAEMON
#endif
#endif
#ifdef KGENMACRO_CONFIG_SSL_PROT_HIGH
#define CONFIG_SSL_PROT_HIGH 1
#else
#undef CONFIG_SSL_PROT_HIGH
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(defined KGENMACRO_CONFIG_AXHTTPD||(KGEN_x210)))||((KGEN_x122)&&((KGEN_x210)||(KGEN_x216))&&(KGEN_x244))))
#ifdef KGENMACRO_CONFIG_HTTP_VERBOSE
#define CONFIG_HTTP_VERBOSE 1
#else
#undef CONFIG_HTTP_VERBOSE
#endif
#endif
#if ((((KGEN_x61)&&((!defined KGENMACRO_CONFIG_SSL_HAS_PEM)||(KGEN_x61)))||(KGEN_x203)))
#ifdef KGENMACRO_CONFIG_SSL_HAS_PEM
#define CONFIG_SSL_HAS_PEM 1
#else
#undef CONFIG_SSL_HAS_PEM
#endif
#endif
#if (((KGEN_x555)&&(KGEN_x556)))
#ifdef KGENMACRO_CONFIG_HTTP_CGI_LAUNCHER
#define CONFIG_HTTP_CGI_LAUNCHER "/usr/bin/cgi"
#else
#define CONFIG_HTTP_CGI_LAUNCHER ""
#endif
#endif
#if (((KGEN_x302)&&(KGEN_x304)))
#ifdef KGENMACRO_CONFIG_SSL_PRIVATE_KEY_PASSWORD
#define CONFIG_SSL_PRIVATE_KEY_PASSWORD "X"
#else
#define CONFIG_SSL_PRIVATE_KEY_PASSWORD ""
#endif
#endif
#if (((KGEN_x260)||((KGEN_x84)&&(KGEN_x232))))
#ifdef KGENMACRO_CONFIG_WIN32_USE_CRYPTO_LIB
#define CONFIG_WIN32_USE_CRYPTO_LIB 1
#else
#undef CONFIG_WIN32_USE_CRYPTO_LIB
#endif
#endif
#if !((((KGEN_x95)&&(KGEN_x96))) && (((KGEN_x100)&&(KGEN_x101))) && (((KGEN_x105)&&(KGEN_x106))) && ((defined KGENMACRO_CONFIG_SSL_SERVER_ONLY||defined KGENMACRO_CONFIG_SSL_CERT_VERIFICATION||defined KGENMACRO_CONFIG_SSL_ENABLE_CLIENT||defined KGENMACRO_CONFIG_SSL_FULL_MODE||defined KGENMACRO_CONFIG_SSL_SKELETON_MODE)) && (((KGEN_x111)&&(KGEN_x112))) && ((defined KGENMACRO_CONFIG_PLATFORM_LINUX||defined KGENMACRO_CONFIG_PLATFORM_CYGWIN||defined KGENMACRO_CONFIG_PLATFORM_WIN32)))
#error
#endif